language: node_js
node_js:
  - 'stable'
before_script:
  - npm prune
jobs:
  include:
    - stage: test
      script:
        - echo "Testing Started ..."
        - echo "Linting ..." && npm run lint:check
after-success:
  - echo "Semantic Release Deployment .."
  - npm run semantic-release
branches:
  only:
    - master
notifications:
  email: false
